/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_marsthink_app_utils_EncryptUtil */

#ifndef _Included_com_marsthink_app_utils_EncryptUtil
#define _Included_com_marsthink_app_utils_EncryptUtil
#define LEN 512
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_marsthink_app_utils_EncryptUtil
 * Method:    aes_encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_marsthink_app_utils_EncryptUtil_aes_1encrypt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_marsthink_app_utils_EncryptUtil
 * Method:    aes_decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_marsthink_app_utils_EncryptUtil_aes_1decrypt
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
